name: .NET MAUI CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    name: Build Android APK
    runs-on: windows-latest  # ✅ Changed to Windows for MAUI compatibility

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install MAUI Workload
        run: |
          dotnet workload install android ios maccatalyst wasm-tools maui
          dotnet workload restore  # ✅ Ensure workloads are restored

      - name: Debug - List Files
        run: Get-ChildItem -Path . -Recurse  # ✅ Debugging step to locate the solution file

      - name: Restore Dependencies
        run: dotnet restore --force  # ✅ Force restore to regenerate assets
        working-directory: ./FeedOptimizationApp

      - name: Build Android App
        run: dotnet build FeedOptimizationApp.csproj -f net8.0-android -c Release
        working-directory: ./FeedOptimizationApp  # ✅ Set correct working directory for build

      - name: Create Android APK
        run: |
          dotnet publish -f net8.0-android -c Release -o ./publish
          move ./publish\*.apk ./publish\App.apk  # Rename output file

      - name: Upload Android Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: ./publish/App.apk

  deploy-android:
    name: Deploy to Google Play
    runs-on: windows-latest
    needs: build-android

    steps:
      - name: Download Android APK
        uses: actions/download-artifact@v3
        with:
          name: Android-APK
          path: ./publish

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Deploy to Google Play Store (Beta)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ""  # Removed secrets for federated identity
          packageName: "com.icarda.feedapp"
          releaseFiles: "./publish/App.apk"
          track: beta
          status: completed

  notify-team:
    name: Notify Team
    runs-on: windows-latest
    needs: [deploy-android]

    steps:
      - name: Send Teams Notification
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"text": "🚀 New MAUI App build deployed to Google Play! 🎉"}' \
               -X POST "https://outlook.office.com/webhook/YOUR_WEBHOOK_URL"





               -X POST "https://outlook.office.com/webhook/YOUR_WEBHOOK_URL"
